# Generated by Django 3.0.3 on 2020-07-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_tracker_app', '0002_auto_20200716_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='PersonalUser',
        ),
    ]
