# Generated by Django 3.0.3 on 2020-07-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_tracker_app', '0003_auto_20200716_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='PersonalUser',
        ),
    ]
