# Generated by Django 3.0.3 on 2020-08-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_tracker_app', '0006_auto_20200730_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showbacklog',
            old_name='user_profile',
            new_name='user',
        ),
    ]
